version: '3.4'

services:
  nle-kafka:
    image: nle-kafka
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 ./src/index.js